/**
 * Shared category constants used across the extension
 * This file exists to prevent circular dependencies between modules
 */

// Canonical taxonomy for categorization
export const CanonicalCategories = [
  "Email",
  "Work",
  "Development",
  "Shopping",
  "Entertainment",
  "Social",
  "News",
  "Finance",
  "Travel",
  "Utilities",
  "AI",
  "Research", // Moved to end to reduce priority bias
];

// Chrome tab group colors available
export const CHROME_TAB_GROUP_COLORS = [
  "grey",
  "blue",
  "red",
  "yellow",
  "green",
  "pink",
  "purple",
  "cyan",
  "orange",
];

// Default color mappings for canonical categories
export const CANONICAL_COLOR_MAP = {
  Email: "blue",
  Work: "yellow",
  Research: "green",
  Development: "purple",
  Shopping: "orange",
  Entertainment: "red",
  Social: "pink",
  News: "cyan",
  Finance: "green",
  Travel: "blue",
  Utilities: "grey",
  AI: "purple",
};

// Comprehensive domain hints for explicit categorization (500+ mappings)
export const DomainHints = {
  // ===== EMAIL & COMMUNICATION =====
  "gmail.com": "Email",
  "mail.google.com": "Email",
  "outlook.com": "Email",
  "outlook.live.com": "Email",
  "office365.com": "Email",
  "yahoo.com": "Email",
  "mail.yahoo.com": "Email",
  "proton.me": "Email",
  "protonmail.com": "Email",
  "fastmail.com": "Email",
  "icloud.com": "Email",
  "aol.com": "Email",
  "yandex.com": "Email",
  "tutanota.com": "Email",
  "mailbox.org": "Email",
  "zoho.com": "Email",
  "hey.com": "Email",
  "slack.com": "Email",
  "teams.microsoft.com": "Email",
  "discord.com": "Email",
  "telegram.org": "Email",
  "whatsapp.com": "Email",
  "signal.org": "Email",
  "messenger.com": "Email",
  "skype.com": "Email",
  "zoom.us": "Email",
  "meet.google.com": "Email",
  "webex.com": "Email",
  "gotomeeting.com": "Email",
  "teamviewer.com": "Email",

  // ===== WORK & PRODUCTIVITY =====
  "docs.google.com": "Work",
  "sheets.google.com": "Work",
  "slides.google.com": "Work",
  "calendar.google.com": "Work",
  "workspace.google.com": "Work",
  "notion.so": "Work",
  "asana.com": "Work",
  "trello.com": "Work",
  "airtable.com": "Work",
  "monday.com": "Work",
  "clickup.com": "Work",
  "basecamp.com": "Work",
  "jira.atlassian.com": "Work",
  "confluence.atlassian.com": "Work",
  "office.com": "Work",
  "office365.com": "Work",
  "sharepoint.com": "Work",
  "onenote.com": "Work",
  "evernote.com": "Work",
  "obsidian.md": "Work",
  "roam.com": "Work",
  "coda.io": "Work",
  "figma.com": "Work",
  "miro.com": "Work",
  "lucidchart.com": "Work",
  "canva.com": "Work",
  "linear.app": "Work",
  "height.app": "Work",
  "todoist.com": "Work",
  "any.do": "Work",
  "microsoft.com": "Work",
  "adobe.com": "Work",
  "salesforce.com": "Work",
  "hubspot.com": "Work",
  "zapier.com": "Work",
  "ifttt.com": "Work",

  // ===== DEVELOPMENT =====
  "github.com": "Development",
  "gitlab.com": "Development",
  "bitbucket.org": "Development",
  "stackoverflow.com": "Development",
  "stackexchange.com": "Development",
  "dev.to": "Development",
  "hashnode.com": "Development",
  "medium.com": "Development",
  "replit.com": "Development",
  "codepen.io": "Development",
  "jsfiddle.net": "Development",
  "codesandbox.io": "Development",
  "glitch.com": "Development",
  "netlify.com": "Development",
  "vercel.com": "Development",
  "heroku.com": "Development",
  "aws.amazon.com": "Development",
  "console.aws.amazon.com": "Development",
  "cloud.google.com": "Development",
  "azure.microsoft.com": "Development",
  "digitalocean.com": "Development",
  "linode.com": "Development",
  "vultr.com": "Development",
  "docker.com": "Development",
  "kubernetes.io": "Development",
  "terraform.io": "Development",
  "ansible.com": "Development",
  "jenkins.io": "Development",
  "circleci.com": "Development",
  "travis-ci.org": "Development",
  "npmjs.com": "Development",
  "pypi.org": "Development",
  "rubygems.org": "Development",
  "packagist.org": "Development",
  "nuget.org": "Development",
  "maven.apache.org": "Development",
  "crates.io": "Development",
  "go.dev": "Development",
  "rust-lang.org": "Development",
  "python.org": "Development",
  "nodejs.org": "Development",
  "reactjs.org": "Development",
  "vuejs.org": "Development",
  "angular.io": "Development",
  "svelte.dev": "Development",
  "nextjs.org": "Development",
  "nuxtjs.org": "Development",
  "laravel.com": "Development",
  "django.com": "Development",
  "flask.palletsprojects.com": "Development",
  "spring.io": "Development",
  "dotnet.microsoft.com": "Development",
  "mysql.com": "Development",
  "postgresql.org": "Development",
  "mongodb.com": "Development",
  "redis.io": "Development",
  "elasticsearch.org": "Development",
  "apache.org": "Development",
  "nginx.org": "Development",
  "postman.com": "Development",
  "insomnia.rest": "Development",

  // ===== ENTERTAINMENT =====
  "youtube.com": "Entertainment",
  "netflix.com": "Entertainment",
  "hulu.com": "Entertainment",
  "disney.com": "Entertainment",
  "disneyplus.com": "Entertainment",
  "hbomax.com": "Entertainment",
  "max.com": "Entertainment",
  "primevideo.com": "Entertainment",
  "paramount.com": "Entertainment",
  "paramountplus.com": "Entertainment",
  "peacocktv.com": "Entertainment",
  "appletv.com": "Entertainment",
  "crunchyroll.com": "Entertainment",
  "funimation.com": "Entertainment",
  "vrv.co": "Entertainment",
  "twitch.tv": "Entertainment",
  "kick.com": "Entertainment",
  "spotify.com": "Entertainment",
  "apple.com": "Entertainment",
  "music.apple.com": "Entertainment",
  "soundcloud.com": "Entertainment",
  "bandcamp.com": "Entertainment",
  "pandora.com": "Entertainment",
  "tidal.com": "Entertainment",
  "deezer.com": "Entertainment",
  "last.fm": "Entertainment",
  "vimeo.com": "Entertainment",
  "dailymotion.com": "Entertainment",
  "imdb.com": "Entertainment",
  "rottentomatoes.com": "Entertainment",
  "metacritic.com": "Entertainment",
  "themoviedb.org": "Entertainment",
  "letterboxd.com": "Entertainment",
  "goodreads.com": "Entertainment",
  "audible.com": "Entertainment",
  "kindle.amazon.com": "Entertainment",
  "steam.com": "Entertainment",
  "epicgames.com": "Entertainment",
  "gog.com": "Entertainment",
  "origin.com": "Entertainment",
  "battle.net": "Entertainment",
  "ubisoft.com": "Entertainment",
  "nintendo.com": "Entertainment",
  "playstation.com": "Entertainment",
  "xbox.com": "Entertainment",
  "itch.io": "Entertainment",
  "roblox.com": "Entertainment",
  "minecraft.net": "Entertainment",
  "fortnite.com": "Entertainment",

  // ===== SOCIAL MEDIA =====
  "facebook.com": "Social",
  "instagram.com": "Social",
  "threads.net": "Social",
  "twitter.com": "Social",
  "x.com": "Social",
  "linkedin.com": "Social",
  "reddit.com": "Social",
  "pinterest.com": "Social",
  "snapchat.com": "Social",
  "tiktok.com": "Social",
  "youtube.com": "Social", // Note: YouTube could be Entertainment or Social
  "tumblr.com": "Social",
  "mastodon.social": "Social",
  "mastodon.online": "Social",
  "bluesky.app": "Social",
  "clubhouse.com": "Social",
  "discord.com": "Social", // Note: Discord could be Email or Social
  "telegram.org": "Social",
  "whatsapp.com": "Social",
  "viber.com": "Social",
  "wechat.com": "Social",
  "line.me": "Social",
  "meetup.com": "Social",
  "eventbrite.com": "Social",

  // ===== NEWS & MEDIA =====
  "nytimes.com": "News",
  "washingtonpost.com": "News",
  "wsj.com": "News",
  "ft.com": "News",
  "economist.com": "News",
  "reuters.com": "News",
// ===== MISSING DOMAINS FROM LOGS =====
  "console.cloud.google.com": "Development",
  "cloud.google.com": "Development",
  "docs.anthropic.com": "AI",
  "console.anthropic.com": "AI",
  "app.glean.com": "Work",
  "glean.com": "Work",
  "duosecurity.com": "Utilities",
  "api-1528adbd.duosecurity.com": "Utilities",
  "console.aws.amazon.com": "Development",
  "aws.amazon.com": "Development",
  "azure.microsoft.com": "Development",
  "console.azure.microsoft.com": "Development",
  "ap.org": "News",
  "bbc.com": "News",
  "bbc.co.uk": "News",
  "cnn.com": "News",
  "fox.com": "News",
  "foxnews.com": "News",
  "msnbc.com": "News",
  "nbcnews.com": "News",
  "abcnews.go.com": "News",
  "cbsnews.com": "News",
  "theguardian.com": "News",
  "independent.co.uk": "News",
  "telegraph.co.uk": "News",
  "bloomberg.com": "News",
  "cnbc.com": "News",
  "marketwatch.com": "News",
  "time.com": "News",
  "newsweek.com": "News",
  "usnews.com": "News",
  "npr.org": "News",
  "pbs.org": "News",
  "politico.com": "News",
  "axios.com": "News",
  "vox.com": "News",
  "buzzfeed.com": "News",
  "huffpost.com": "News",
  "slate.com": "News",
  "salon.com": "News",
  "theatlantic.com": "News",
  "newyorker.com": "News",
  "wired.com": "News",
  "techcrunch.com": "News",
  "theverge.com": "News",
  "engadget.com": "News",
  "arstechnica.com": "News",
  "9to5mac.com": "News",
  "macrumors.com": "News",
  "androidpolice.com": "News",

  // ===== SHOPPING =====
  "amazon.com": "Shopping",
  "amazon.co.uk": "Shopping",
  "amazon.de": "Shopping",
  "amazon.ca": "Shopping",
  "ebay.com": "Shopping",
  "etsy.com": "Shopping",
  "alibaba.com": "Shopping",
  "aliexpress.com": "Shopping",
  "walmart.com": "Shopping",
  "target.com": "Shopping",
  "bestbuy.com": "Shopping",
  "costco.com": "Shopping",
  "homedepot.com": "Shopping",
  "lowes.com": "Shopping",
  "macys.com": "Shopping",
  "nordstrom.com": "Shopping",
  "saks.com": "Shopping",
  "bloomingdales.com": "Shopping",
  "zappos.com": "Shopping",
  "wayfair.com": "Shopping",
  "overstock.com": "Shopping",
  "newegg.com": "Shopping",
  "bhphotovideo.com": "Shopping",
  "adorama.com": "Shopping",
  "sephora.com": "Shopping",
  "ulta.com": "Shopping",
  "nike.com": "Shopping",
  "adidas.com": "Shopping",
  "lululemon.com": "Shopping",
  "patagonia.com": "Shopping",
  "rei.com": "Shopping",
  "backcountry.com": "Shopping",
  "zara.com": "Shopping",
  "hm.com": "Shopping",
  "uniqlo.com": "Shopping",
  "gap.com": "Shopping",
  "oldnavy.com": "Shopping",
  "jcrew.com": "Shopping",
  "bananarepublic.com": "Shopping",
  "anthropologie.com": "Shopping",
  "urbanoutfitters.com": "Shopping",
  "asos.com": "Shopping",
  "boohoo.com": "Shopping",
  "shein.com": "Shopping",
  "temu.com": "Shopping",
  "wish.com": "Shopping",

  // ===== FINANCE =====
  "paypal.com": "Finance",
  "venmo.com": "Finance",
  "cashapp.com": "Finance",
  "zelle.com": "Finance",
  "stripe.com": "Finance",
  "square.com": "Finance",
  "revolut.com": "Finance",
  "wise.com": "Finance",
  "remitly.com": "Finance",
  "westernunion.com": "Finance",
  "moneygram.com": "Finance",
  "chase.com": "Finance",
  "bankofamerica.com": "Finance",
  "wellsfargo.com": "Finance",
  "citi.com": "Finance",
  "capitalone.com": "Finance",
  "usbank.com": "Finance",
  "pnc.com": "Finance",
  "truist.com": "Finance",
  "regions.com": "Finance",
  "ally.com": "Finance",
  "discover.com": "Finance",
  "americanexpress.com": "Finance",
  "visa.com": "Finance",
  "mastercard.com": "Finance",
  "hsbc.com": "Finance",
  "barclays.co.uk": "Finance",
  "lloyds.com": "Finance",
  "natwest.com": "Finance",
  "santander.com": "Finance",
  "rbs.co.uk": "Finance",
  "coinbase.com": "Finance",
  "binance.com": "Finance",
  "kraken.com": "Finance",
  "gemini.com": "Finance",
  "crypto.com": "Finance",
  "robinhood.com": "Finance",
  "etrade.com": "Finance",
  "schwab.com": "Finance",
  "fidelity.com": "Finance",
  "vanguard.com": "Finance",
  "tdameritrade.com": "Finance",
  "interactivebrokers.com": "Finance",
  "webull.com": "Finance",
  "sofi.com": "Finance",
  "acorns.com": "Finance",
  "stash.com": "Finance",
  "betterment.com": "Finance",
  "wealthfront.com": "Finance",
  "mint.com": "Finance",
  "personalcapital.com": "Finance",
  "ynab.com": "Finance",
  "quicken.com": "Finance",

  // ===== TRAVEL =====
  "booking.com": "Travel",
  "expedia.com": "Travel",
  "priceline.com": "Travel",
  "kayak.com": "Travel",
  "orbitz.com": "Travel",
  "travelocity.com": "Travel",
  "hotels.com": "Travel",
  "airbnb.com": "Travel",
  "vrbo.com": "Travel",
  "homeaway.com": "Travel",
  "tripadvisor.com": "Travel",
  "yelp.com": "Travel",
  "foursquare.com": "Travel",
  "maps.google.com": "Travel",
  "waze.com": "Travel",
  "uber.com": "Travel",
  "lyft.com": "Travel",
  "delta.com": "Travel",
  "united.com": "Travel",
  "american.com": "Travel",
  "southwest.com": "Travel",
  "jetblue.com": "Travel",
  "spirit.com": "Travel",
  "frontier.com": "Travel",
  "alaska.com": "Travel",
  "hawaiian.com": "Travel",
  "britishairways.com": "Travel",
  "lufthansa.com": "Travel",
  "klm.com": "Travel",
  "airfrance.com": "Travel",
  "emirates.com": "Travel",
  "qantas.com": "Travel",
  "singaporeair.com": "Travel",
  "marriott.com": "Travel",
  "hilton.com": "Travel",
  "hyatt.com": "Travel",
  "ihg.com": "Travel",
  "choicehotels.com": "Travel",
  "bestwestern.com": "Travel",
  "accor.com": "Travel",
  "radisson.com": "Travel",
  "wyndham.com": "Travel",

  // ===== UTILITIES =====
  "drive.google.com": "Utilities",
  "dropbox.com": "Utilities",
  "onedrive.live.com": "Utilities",
  "icloud.com": "Utilities",
  "box.com": "Utilities",
  "mega.nz": "Utilities",
  "pcloud.com": "Utilities",
  "sync.com": "Utilities",
  "mediafire.com": "Utilities",
  "wetransfer.com": "Utilities",
  "sendspace.com": "Utilities",
  "filemail.com": "Utilities",
  "1password.com": "Utilities",
  "lastpass.com": "Utilities",
  "bitwarden.com": "Utilities",
  "dashlane.com": "Utilities",
  "keepass.info": "Utilities",
  "nordpass.com": "Utilities",
  "adobe.com": "Utilities",
  "canva.com": "Utilities",
  "photoshop.com": "Utilities",
  "figma.com": "Utilities",
  "sketch.com": "Utilities",
  "invision.com": "Utilities",
  "zeplin.io": "Utilities",
  "loom.com": "Utilities",
  "calendly.com": "Utilities",
  "acuityscheduling.com": "Utilities",
  "doodle.com": "Utilities",
  "when2meet.com": "Utilities",

  // ===== AI & ML =====
  "openai.com": "AI",
  "chat.openai.com": "AI",
  "anthropic.com": "AI",
  "claude.ai": "AI",
  "google.com": "AI", // For Bard/Gemini
  "bard.google.com": "AI",
  "gemini.google.com": "AI",
  "character.ai": "AI",
  "replika.ai": "AI",
  "jasper.ai": "AI",
  "copy.ai": "AI",
  "writesonic.com": "AI",
  "grammarly.com": "AI",
  "notion.ai": "AI",
  "midjourney.com": "AI",
  "dall-e.com": "AI",
  "stable-diffusion.com": "AI",
  "runway.ml": "AI",
  "huggingface.co": "AI",
  "replicate.com": "AI",
  "cohere.ai": "AI",
  "scale.ai": "AI",
  "wandb.ai": "AI",
  "weights.biases.com": "AI",
  "tensorboard.dev": "AI",
  "kaggle.com": "AI",
  "papers.withcode.com": "AI",

  // ===== RESEARCH (Academic/Scholarly Only) =====
  "scholar.google.com": "Research",
  "pubmed.ncbi.nlm.nih.gov": "Research",
  "arxiv.org": "Research",
  "jstor.org": "Research",
  "researchgate.net": "Research",
  "academia.edu": "Research",
  "ieee.org": "Research",
  "acm.org": "Research",
  "springer.com": "Research",
  "elsevier.com": "Research",
  "wiley.com": "Research",
  "nature.com": "Research",
  "science.org": "Research",
  "cell.com": "Research",
  "pnas.org": "Research",
  "sciencedirect.com": "Research",
  "webofscience.com": "Research",
  "scopus.com": "Research",
};
