#!/usr/bin/env bash
set -euo pipefail

# Bootstrap local, untracked artifacts for development builds.
# - Prompts for your Groq API key and generates src/llm/providers/GroqKey.js (git-ignored)
# - Ensures local-only ai-docs/ directory exists (git-ignored)
# See docs: [docs/SAFE_GIT_PUSH.md](docs/SAFE_GIT_PUSH.md)

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"
cd "$ROOT_DIR"

echo "==> Bootstrap: preparing local-only assets (no secrets committed)"

# Ensure required tools
if ! command -v base64 >/dev/null 2>&1; then
  echo "Error: 'base64' command not found. Install coreutils or ensure macOS base64 is available." >&2
  exit 1
fi

# Ensure local-only docs directory (ignored by Git)
if [ ! -d "ai-docs" ]; then
  mkdir -p "ai-docs"
  echo "Created local directory: ai-docs/ (ignored by Git)"
fi

# Confirm GroqKey.js is ignored by Git (safety check)
if ! grep -qE '^src/llm/providers/GroqKey\.js$' .gitignore; then
  echo "Warning: src/llm/providers/GroqKey.js is not explicitly ignored in .gitignore." >&2
  echo "Add a line to .gitignore if needed: src/llm/providers/GroqKey.js" >&2
fi

# Read key either from env or prompt securely
if [ -z "${GROQ_KEY:-}" ]; then
  read -rs -p "Enter Groq API key (starts with gsk_): " GROQ_KEY
  echo
fi

if [ -z "$GROQ_KEY" ]; then
  echo "No key provided; aborting." >&2
  exit 1
fi

if [[ "$GROQ_KEY" != gsk_* ]]; then
  echo "Warning: Key does not start with 'gsk_'. Continuing..." >&2
fi

# Base64 encode without trailing newline
B64="$(printf "%s" "$GROQ_KEY" | base64)"

TARGET="src/llm/providers/GroqKey.js"
mkdir -p "$(dirname "$TARGET")"

cat > "$TARGET" <<EOF
/**
 * Local Embedded Groq API Key (Base64)
 * Generated by scripts/bootstrap-local.sh. Do NOT commit this file.
 * See .gitignore and [docs/SAFE_GIT_PUSH.md](docs/SAFE_GIT_PUSH.md:1).
 */
export const EMBEDDED_KEY_B64 = "$B64";
EOF

echo "Wrote \$TARGET with embedded base64 key."
echo "Verifying ignore status:"
if command -v git >/dev/null 2>&1; then
  git check-ignore -v src/llm/providers/GroqKey.js || echo "Note: ensure .gitignore contains 'src/llm/providers/GroqKey.js'"
else
  echo "Git not available to verify ignore status."
fi

echo "==> Bootstrap complete."
echo "Next steps:"
echo "  1) npm install"
echo "  2) npm run build"
echo "  3) unzip -l dist/*.zip | grep -E 'src/llm/providers/GroqKey.js|manifest.json'"